### ISSUE TITLE
TR classes for the right side table

### ISSUE THREAD

**Issue by cydoval** [ucdavis/AD419ExpenseAssociation#17]
In the top most right table (what i'm calling the active table) I'd like some tr classes like you've done to the left table.

1) if u click on an associated expense in the left column, i'd like those associated projects to have a tr of 'expense-associated' 

I think thats it, cause if it doesn't have that class i'll just make it blue which will be the pending / unassociated color

**Comment by srkirkland** [comment]
I'm thinking we leave this out for now because it gets confusing as soon as any changes are made.  like does the classname go away if you change the percentage?  what about if you add in another expense?

**Comment by srkirkland** [comment]
decided to leave out for now
