### ISSUE TITLE
204 Expenses in old AD419 web app vs. data helper

### ISSUE THREAD

**Issue by srkirkland** [ucdavis/AD419ExpenseAssociation#56]

**Comment by srkirkland** [comment]
Not exactly sure what this was supposed to be, we should ask

**Comment by taylorkj** [comment]
The old AD-419 application had the a way to view the actual 204 expense associations under the "Report Administration" tab named "204 project associations", plus it also allowed the viewing of the other 201, 202, 205, and 22F (field station expenses),   that the system had found and auto-associated.  These expenses and their corresponding associations are not visible using either the old of new application's reporting modules; however, it is useful to see what expenses were found by the system and which projects they were auto-associated to.  Therefore, this request, if I am recalling correctly, was to add a similar feature to the new AD-419 Association web app.  Basically Shannon was asking for a a way to look under the covers at these "hidden" SFNs, as the are not displayed in the association's U.I.  Perhaps an additional tab/feature viewable by admin users?

**Comment by taylorkj** [comment]
![image (7)](https://user-images.githubusercontent.com/583137/203444730-f82acb96-62b4-4ea0-90d9-c35cf1744ddd.png)

**Comment by taylorkj** [comment]
Just add the 204s to the drop-down menu that currently contains 201, 202, 205, and 22F, so that it contains 201,202,204,205 and 22F.  Please let me know if you'd like me to research which sproc is called to populate the list.  Thanks, Ken.

**Comment by taylorkj** [comment]
SQL would be something like the following:  Filtering for specific SFN(s) and Department(s) can be done in application.
```
SELECT 
	Expenses.Exp_SFN SFN,  
	Associations.OrgR, 
	Project.Project, 
	Project.Accession,Project.inv1, 
	Associations.Expenses 
FROM            Expenses INNER JOIN
                         ReportingOrg ON Expenses.OrgR = ReportingOrg.OrgR INNER JOIN
                         Associations ON Expenses.ExpenseID = Associations.ExpenseID INNER JOIN
                         Project ON Associations.Accession = Project.Accession
WHERE Expenses.Exp_SFN IN ('201', '202', '204', '205', '22F') and Associations.OrgR LIKE '%'

ORDER BY SFN, Project, Associations.OrgR, [inv
```1]
