### ISSUE TITLE
Reorder columns on Expense Associations page

### ISSUE THREAD

**Issue by srkirkland** [ucdavis/AD419ExpenseAssociation#59]
> We’d like the order to be switched between the Project and the PI so Project is on the right and PI is in the middle. This will make it visually easier for users to ensure they are selecting the correct PI. 

![image](https://user-images.githubusercontent.com/202753/146415192-7cc9bc4d-2c0e-4d91-b0a9-c42dfca6f0cd.png)

**Comment by sprucely** [comment]
Implemented by #67
